//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTCApi.Model.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string LoginName { get; set; }
        public string PasswordHash { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> BirthOfDate { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Qualifications { get; set; }
        public string BankAccount { get; set; }
        public string BHYT { get; set; }
        public string MST { get; set; }
        public string BHXH { get; set; }
        public string CMTND { get; set; }
        public string JobDescription { get; set; }
        public string Telephone { get; set; }
        public string HandPhone { get; set; }
        public string HomeAddress { get; set; }
        public string Resident { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> Status { get; set; }
        public string Communication { get; set; }
        public Nullable<System.DateTime> PassExpireDate { get; set; }
        public Nullable<bool> IsCashier { get; set; }
        public Nullable<int> CashierNo { get; set; }
        public string EmailCom { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> StartWorking { get; set; }
        public Nullable<int> UserGroupID { get; set; }
        public Nullable<int> UserGroupSXID { get; set; }
        public Nullable<int> MainViewID { get; set; }
        public string Position { get; set; }
        public Nullable<bool> IsSetupFunction { get; set; }
        public string ImagePath { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<int> isAdminSale { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> TeamID { get; set; }
        public Nullable<int> Leader { get; set; }
    }
}
